apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-autoscale-demo-ondemand
  labels:
    demo: karpenter-ondemand
spec:
  replicas: 10
  selector:
    matchLabels:
      app: autoscale-demo
  template:
    metadata:
      labels:
        app: autoscale-demo
    spec:
      # Force pods to on-demand nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values: ["ondemand-nodepool"]
              - key: karpenter.sh/capacity-type
                operator: In
                values: ["on-demand"]     
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"  
            limits:
              cpu: "500m"
              memory: "256Mi"