apiVersion: v1
kind: Service
metadata:
  name: catalog-mysql  #This must match with serviceName: catalog-mysql  from stateful
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/owner: retail-store-sample
spec:
  clusterIP: None   # Headless service
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
  selector: # This must match the content of selector: matchLabels from stateful
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/owner: retail-store-sample