apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:dercioanselmo/argocd-example-apps-labs-private.git
    targetRevision: HEAD
    path: helm-guestbook
 #   helm:  --> If we want not to prune the previous 
 #     valuesObject:
 #       fullnameOverride: guestbook-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true